var IDENTITY_FRAME = 0,
    PROTOCOL_FRAME = 1,
    TYPE_FRAME     = 2,
    RID_FRAME      = 3,
    ADDRESS_FRAME  = 4,
    HEADERS_FRAME  = 5,
    STATUS_FRAME   = 6,
    PAYLOAD_FRAME  = 7;

var framesHelper = {
  IDENTITY_FRAME: IDENTITY_FRAME,
  PROTOCOL_FRAME: PROTOCOL_FRAME,
  TYPE_FRAME: TYPE_FRAME,
  RID_FRAME: RID_FRAME,
  ADDRESS_FRAME: ADDRESS_FRAME,
  HEADERS_FRAME: HEADERS_FRAME,
  STATUS_FRAME: STATUS_FRAME,
  PAYLOAD_FRAME: PAYLOAD_FRAME
};

module.exports = framesHelper;
